language: go

go:
  - 1.8.x
  - 1.9.x
  - "1.10.x"

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

before_script:
  - go vet
  - go build ./vendor/github.com/golang/lint/golint
  - ./golint -set_exit_status

script:
  - go test -v
